# Snakemake pipeline for scRNA-seq data using Cell Ranger and Seurat with Docker containers
import os, sys
import pandas as pd 

include: "rules/rule_mkfastq.smk"
# include: "rules/rule_mkvdjref.smk"

print("bcl folder  : " + bcl_folder)
print(samples)

# Define rules
rule all:
    input:
        flag = os.path.join(outdir, "mkfastq.sucess")  
