samples_csv:  "samples.csv" 

start_with_bcl: true  # Set to false if starting with FASTQ files
bcl_folder: "cellranger-tiny-bcl-1.2.0"
flowcell_id: "H35KCBCXY"

fastq_path: #"/path/to/fastqs"  # Only used if start_with_bcl is false
transcriptome: "refdata-cellranger-hg19-1.2.0"

pass_expect_cells: false # true  # This is where you specify the expected cell count
expect_cells: 3000  # This is where you specify the expected cell count
pass_force_cells: false #2000   # Optional: This can also be specified
force_cells:  #2000   # Optional: This can also be specified

create_bam: true  # Set to true if you want to create BAM files during count

resources:
  localcores: 8  # Set the number of cores to use (e.g., 16)
  localmem: 64  # Set the amount of memory to use in GB

use_feature_ref: false  # Indicates whether to use the --feature-ref parameter
use_libraries: false  # Indicates whether to use the --libraries parameter

feature_ref: "feature_ref.csv" #"/path/to/feature_ref.csv"  # Path to the Feature Reference CSV file (optional)
libraries_csv: "libraries.csv" #"/path/to/libraries.csv"  # Path to the Libraries CSV file (optional)

# Important
# cellranger aggr is NOT designed for aggregating multiple sequencing runs of the same library, 
# for example, resequencing the same library to increase read depth.
# In this scenario, you must specify all FASTQ files (fastqs field) in a single analysis of either cellranger count or multi.

aggregate: false # Set to false if you do not want to run cellranger aggr
aggregation_id: "test" # Required. A unique run ID string: e.g. AGG123
aggregation_csv: "aggregation.csv" # Required. Path to the aggregation CSV file containing the list of molecule_info.h5 files.
reanalyze: false  # Set to false if you do not want to run cellranger reanalyze
