---
snakefile: Snakefile
cores: 32
latency-wait:
reason: True
show-failed-logs: True
keep-going: True
printshellcmds: True
rerun-incomplete: True
restart-times:

# singularity
use-singularity: True
singularity-args: "--bind /home/debojyoti/Projects/core_facility/"
# # Cluster submission
# jobname: "{rule}.{jobid}"              # Provide a custom name for the jobscript that is submitted to the cluster.
# max-jobs-per-second: 1                 #Maximal number of cluster/drmaa jobs per second, default is 10, fractions allowed.
# max-status-checks-per-second: 10       #Maximal number of job status checks per second, default is 10
# jobs: 400                              #Use at most N CPU cluster/cloud jobs in parallel.
# cluster: "sbatch --output=\"jobs/{rule}/slurm_%x_%j.out\" --error=\"jobs/{rule}/slurm_%x_%j.log\" --mem={resources.mem_mb} --time={resources.runtime}"
# # Job resources
# set-resources:
#     - printContent:mem_mb=2000
#     - printContent:runtime=00:01:00
