bcl_folder_paths: "../gosia_single_cell_runs/bcl_folder_paths.csv"
# bcl_folder_paths: "../gosia_single_cell_runs/bcl_folder_paths_count_only.csv"
# "../gosia_single_cell_runs/bcl_folder_paths.csv" # gex + vdj

resources:
  localcores: 8
  localmem: 32
  max_cores: 48
  max_memory: 128

additional_arguments: " --delete-undetermined "
