samples_csv: "../gosia_single_cell_runs/240220_VH01167_29_AAFHTGTM5/SampleSheet.csv"

output_multi: ""

transcriptome: "../refdata-gex-GRCh38-2020-A"
vdj_reference: "../refdata_cellranger_vdj_GRCh38_alts_ensembl_710"

resources:
  localcores: 8 # Set the number of cores to use (e.g., 16)
  localmem: 64 # Set the amount of memory to use in GB

use_feature_ref: False # Indicates whether to use the --feature-ref parameter
use_libraries: False # Indicates whether to use the --libraries parameter

feature_ref: "feature_ref.csv" # # Path to the Feature Reference CSV file (optional)
libraries_csv: "libraries.csv" # Path to the Libraries CSV file (optional)

