
bcl_folder: "../test/cellranger-tiny-bcl-1.2.0" 

flowcell_id: "H35KCBCXY"  # needs to be exact if simple sample sheet csv is used
outputdir: "tiny_bcl"

resources:
  localcores: 32  # Set the number of cores to use (e.g., 16)
  localmem: 128   # Set the amount of memory to use in GB

IEM_samplesheet: True # or the sample sheet is of type "simple csv"
samples_csv:  "../test/cellranger-tiny-bcl-samplesheet-1.2.0.csv" 
