
bcl_folder: "../test/cellranger-tiny-bcl-1.2.0" 

outputdir: "tiny_bcl"

resources:
  localcores: 32  # Set the number of cores to use (e.g., 16)
  localmem: 128   # Set the amount of memory to use in GB

IEM_samplesheet: True # or the sample sheet is of type "simple csv"
samples_csv:  "../test/cellranger-tiny-bcl-samplesheet-1.2.0.csv" 

additional_argmuments: #
