bcl_folder_paths: "/home/debojyoti/Projects/core_facility/cellranger_snakemake_tests/bcl_folder_paths_multi.csv"
# bcl_folder_paths: "/home/debojyoti/Projects/core_facility/cellranger_snakemake_tests/gosia_single_cell_runs/bcl_folder_paths_count_only.csv"

results_directory: "/home/debojyoti/Projects/core_facility/cellranger_snakemake_tests/gex_count_test_four"

resources:
  localcores: 8
  localmem: 32
  max_cores: 48
  max_memory: 128

additional_arguments: " --delete-undetermined "
