output_vdj: "../gosia_single_cell_runs/output_240220/vdj_results"

vdj_reference: "../refdata_cellranger_vdj_GRCh38_alts_ensembl_710"
paths2fastq4vdj_file: "../gosia_single_cell_runs/output_240220/mkfastq.sucess.csv"

resources:
  localcores: 4
  localmem: 8
  max_cores: 8
  max_memory: 16

additional_arguments: "" # required
